### PR TITLE
Fixed Negative HP

### PR DESCRIPTION
**Pull request by alnyan**
Just kills player when HP is lower than zero.

### CODE REVIEW

**Comment by JeromSar** [comment]
@Awesome2K First of all, thanks for contributing.

This looks good, but needs a small change and a formatting fix. Then we're all good. :)

P.S. How did you find us? Why are you interested in this project?

Jerom

**Comment by alnyan** [comment]
Replaced it.

**Comment by alnyan** [comment]
> P.S. How did you find us? Why are you interested in this project?

Just searched GitHub for some java projects to contribute.

**Comment by JeromSar** [comment]
@Awesome2K Ah well thanks for contributing.

One more thing: I see that you've used tabs for indentation, while 4 spaces is the standard on this repository. See [this link](http://programmers.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e). If you could fix that, then I see no reason to keep this PR from being merged. :)

**Comment by alnyan** [comment]
Okay :)

**Comment by alnyan** [comment]
OK, i've replaced tabs with spaces.

**Comment by JeromSar** [comment]
Merged in https://github.com/Goldiriath/Goldiriath/commit/07aff694250d313aca9332e300295dea124a882f.

Thanks for contributing!

**Pull request closed without merging**
